/*
         // pqs.data.materialSettings.surfaceMaterial;
         _AlbedoScaledTex
         _NormalScaledTex
         _PackedScaledTex
         _BiomeMaskTex
         _SubzoneMaskTex
         _GlobalGradienceTex
         _GlobalCurvatureTex
         _LargeCurvatureR
         _LargeCurvatureG
         _LargeCurvatureB
         _LargeCurvatureA
         _LargeGradienceR
         _LargeGradienceG
         _LargeGradienceB
         _LargeGradienceA
         _LargeNormalR
         _LargeNormalG
         _LargeNormalB
         _LargeNormalA
         _MidCurvatureR
         _MidCurvatureG
         _MidCurvatureB
         _MidCurvatureA
         _MidGradienceR
         _MidGradienceG
         _MidGradienceB
         _MidGradienceA
         _MidNormalR
         _MidNormalG
         _MidNormalB
         _MidNormalA
         _Subzone3CurvatureR
         _Subzone3CurvatureG
         _Subzone3CurvatureB
         _Subzone3CurvatureA
         _Subzone3GradienceR
         _Subzone3GradienceG
         _Subzone3GradienceB
         _Subzone3GradienceA
         _Subzone3NormalR
         _Subzone3NormalG
         _Subzone3NormalB
         _Subzone3NormalA
         _Subzone4CurvatureR
         _Subzone4CurvatureG
         _Subzone4CurvatureB
         _Subzone4CurvatureA
         _Subzone4GradienceR
         _Subzone4GradienceG
         _Subzone4GradienceB
         _Subzone4GradienceA
         
         _Subzone4NormalG
         _Subzone4NormalB
         _Subzone4NormalA
         
         _ShorelineTex


*/
