PM.Science:PatchTechNodes("Add1v_1x1Tank_stock"):Conflicts("WMCC"):Named("tNode_1v_utility_01"):Do(function (node)
    node.UnlockedPartsIDs:Append("KLSS_life_support_tank_1v_1x1")
end)
PM.Science:PatchTechNodes("Add1v_1x1Tank_wmcc"):Needs("WMCC"):After("WMCC"):Named("wmcc_crewed_rocketry"):Do(function (node)
    node.UnlockedPartsIDs:Append("KLSS_life_support_tank_1v_1x1")
end)

PM.Science:PatchTechNodes("Add2v_1x1Tank_stock"):Conflicts("WMCC"):Named("tNode_2v_payload"):Do(function (node)
    node.UnlockedPartsIDs:Append("KLSS_life_support_tank_2v_1x1")
end)
PM.Science:PatchTechNodes("Add2v_1x1Tank_wmcc"):Needs("WMCC"):After("WMCC"):Named("wmcc_larger_payloads"):Do(function (node)
    node.UnlockedPartsIDs:Append("KLSS_life_support_tank_2v_1x1")
end)

PM.Science:PatchTechNodes("Add0v_RadialStorage_stock"):Conflicts("WMCC"):Named("tNode_1v_rover"):Do(function (node)
    node.UnlockedPartsIDs:Append("KLSS_storage_0v_radial")
end)
PM.Science:PatchTechNodes("Add0v_RadialStorage_wmcc"):Needs("WMCC"):After("WMCC"):Named("wmcc_buggies"):Do(function (node)
    node.UnlockedPartsIDs:Append("KLSS_storage_0v_radial")
end)

PM.Science:PatchTechNodes("Add2v_1x2Storage_stock"):Conflicts("WMCC"):Named("tNode_2v_docking"):Do(function (node)
    node.UnlockedPartsIDs:Append("KLSS_storage_2v_1x2")
end)
PM.Science:PatchTechNodes("Add2v_1x2Storage_wmcc"):Needs("WMCC"):After("WMCC"):Named("wmcc_early_docking_ports"):Do(function (node)
    node.UnlockedPartsIDs:Append("KLSS_storage_2v_1x2")
end)

PM.Science:PatchTechNodes("Add2v_RadialStorage_stock"):Conflicts("WMCC"):Named("tNode_3v_payload_01"):Do(function (node)
    node.UnlockedPartsIDs:Append("KLSS_storage_2v_radial")
end)
PM.Science:PatchTechNodes("Add2v_RadialStorage_wmcc"):Needs("WMCC"):After("WMCC"):Named("wmcc_heavy_payloads"):Do(function (node)
    node.UnlockedPartsIDs:Append("KLSS_storage_2v_radial")
end)

PM.Science:PatchTechNodes("Add2v_GreenhouseAndComposter_stock"):Conflicts("WMCC"):Named("tNode_2v_electronics_02"):Do(function (node)
    node.UnlockedPartsIDs:Append("KLSS_greenhouse_2v_long")
    node.UnlockedPartsIDs:Append("KLSS_composter_2v_short")
end)
PM.Science:PatchTechNodes("Add2v_GreenhouseAndComposter_wmcc"):Needs("WMCC"):After("WMCC"):Named("wmcc_advanced_electronics_plus"):Do(function (node)
    node.UnlockedPartsIDs:Append("KLSS_greenhouse_2v_long")
    node.UnlockedPartsIDs:Append("KLSS_composter_2v_short")
end)