---@class KLSS.Constants
local M = {}
M.SECONDS_PER_DAY = 21600
M.WATER_PER_DAY = 3.0
M.FOOD_PER_DAY = 0.001
M.OXYGEN_PER_DAY = 0.001
M.RECYCLER_EFFICIENCY = 0.75
M.POD_CAPACITY_DAYS = 7.0
M.EVA_CAPACITY_DAYS = 1.0
return M